services:
  - type: web
    name: ffmeditor
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WORKERS
        value: "1"
      - key: PRESET_MODE
        value: balanced
      - key: MAX_UPLOAD_MB
        value: "200"
      - key: HWACCEL
        value: none
